### ISSUE TITLE
SparseConv decoder

### ISSUE THREAD

**Issue by ShilinC** [kashyap7x/QuadNet#4]
Hi,

Sorry about asking another question here... when I looked at the decoder part of the SparseConv you had (e.g., ResNetTransposeSparse() and TransBasicBlockSparse()), I found that you use dense deconvolution:

```
scn.Sequential(
            scn.SparseToDense(2,inplanes),
            nn.ConvTranspose2d(inplanes, planes, kernel_size=2, stride=stride, padding=0, output_padding=0, bias=False),
            scn.DenseToSparse(2)
)
```
Looks like SparseConvNet has methods called scn.Deconvolution() and scn.UnPooling(). Is there any specific reason that you need to use dense ConvTranspose2d() here instead of the sparse version? 

Because if ConvTranspose2d() is used, then the network cannot handle a very large resolution since you need to convert sparse tensor to a dense tensor array first. If the spatial resolution is very high, then it can be a bottleneck in the decoder.

Thanks!

**Comment by kashyap7x** [comment]
As I recall, scn.Deconvolution() and scn.UnPooling() do not implement the required functionality. These layers do not change the number of active locations in the sparse tensor, instead "routing" the input feature to one of the four pixels in the following upsampled layer, based on a provided index. As such, they are normally used in the decoder in combination with a sparse encoder from the scn library, so that the indices for routing are already known. In QGNs, we instead require that the feature be copied to all the four pixels in the following layer, and use a standard dense encoder.

If this work-around is becoming a bottleneck at higher resolutions, I think a sparse version of the same functionality should be possible to implement. Initially, you could apply scn.Deconvolution() 4 times using the 4 different pooling indices, and then combine the 4 resulting sparse tensors. Unfortunately, I had not thought of this solution at the time of submission.
